name: openflamingo
channels:
  - defaults
dependencies:
  - python=3.9
  - conda-forge::openjdk
  - pip
  - pip:
    - -r requirements.txt
    - -r requirements-training.txt
    - -r requirements-eval.txt
    - -e .
